blank_issues_enabled: false
contact_links:
  - name: BioBakery Forum
    url: https://forum.biobakery.org/
    about: The bioBakery support forum provides software support and tutorials for methods for microbial community profiling developed by the Huttenhower lab. Please create a new topic in the bioBakery support forum to submit a bug report or feature request.
