
name: Close Issues
on:
  issues:
    types: [opened]
jobs:
  auto_close_all_issues:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/close-issue@v1
        with:
          comment: |
            Thank you for creating this issue. 
            We currently field issues through our [bioBakery Discourse Support Forum](https://forum.biobakery.org/). 
            If you would please post the issue to discourse we would be happy to sync up with you to get it resolved.
